name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias
        run: sudo apt-get update && sudo apt-get install -y gcc make valgrind gnuplot

      - name: Correr tests with Valgrind
        run: make tests

      - name: Ejecutar el experimento (benchmark)
        run: make run
